### PR TITLE
Issue-2: Remove formatting for undefined step errors

### PR DESCRIPTION
**Pull request by ptrimble**
I have no idea how to test the output in Golang. I have a few ideas but all seem really, really hacky. Instead of polluting this space with my guesses I wanted to see what others thought.

Fixes this: https://github.com/sittercity/gocumber/issues/2

### CODE REVIEW

**Comment by zombor** [comment]
No test? :)

**Comment by ptrimble** [comment]
I have no idea how to test the output in Golang. I have a few ideas but all seem really, really hacky. Instead of polluting this space with my guesses I wanted to see what others thought.

**Comment by cbandy** [comment]
http://golang.org/pkg/testing/#hdr-Examples

**Comment by ptrimble** [comment]
My main hurdle is how to print out the output of the local pieces. Here is the relevant test: https://github.com/sittercity/gocumber/blob/master/gocumber_test.go#L19-L28

I did it this way so that the overall test did not fail, just the 'local' test. But the issue is that I don't see a clean way to get the output from the 'local' test.  In [testing.go](http://golang.org/src/testing/testing.go) the report/log stuff is all private. What would I call to get that output?

And if I use the 'real' testing object then the actual test fails.

**Comment by ptrimble** [comment]
I don't think there is a good way to do this. I see methods deep in the testing.go file but there are scary comments like this is 'not subject to the Go 1 compatibility document'. 

I was thinking I could somehow create a full test framework like `go test` does but that would require me to call into these scary methods....

**Comment by cbandy** [comment]
We could export a gocumber interface that `testing.T` implements and use a mock/spy.

**Comment by ptrimble** [comment]
@cbandy @zombor Eh? Eh?

**Comment by zombor** [comment]
:package:

**Pull request merged**
